# Generated by Django 2.2.24 on 2022-01-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211224_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
    ]
