# Generated by Django 2.2.24 on 2023-03-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_customuser_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imageUrl',
            field=models.TextField(null=True),
        ),
    ]
