# Generated by Django 2.2.24 on 2023-03-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0003_auto_20230331_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
